version: '3'

services:
  app:
    build: .
    # better not to share, to allow different node_module binaries. Disable for special cases only
    # volumes:
    #   - .:/app:cached
    ports:
      - 3001:3000

